### ISSUE TITLE
State of this project?

### ISSUE THREAD

**Issue by tramuntanal** [bostko/doc2text#4]
Hi @bostko ,
I'm working in updaing this project (I have a PR in progress) and find that there are even some bugs mainly invalid invokations due to incomplete namespaces. It seems that all is in the middle of a refactor.

So I'm aking myself if you are going to accept PRs and release a new version of the gem, or you prefer your project to continue in some other way?

**Comment by bostko** [comment]
Hi @tramuntanal,
Thanks for the interest on the topic. I'd love to help and review Pull Requests!

**Comment by tramuntanal** [comment]
Thanks for your feedback @bostko ,
I currently have [this](https://github.com/bostko/doc2text/pull/3) PR ready :smiley:

**Comment by tramuntanal** [comment]
Hi @bostko ,
I need to perform many updates on the current version of the gem before the end of month.
Mainly fixing and completing the parsing of odt documents (PR before mentioned), and probably completing the parsing of docx documents.

Would you like and have the time to update your gem during this November? or it is better for us to definitively work with our fork?
(thanks for your feedback)

**Comment by bostko** [comment]
Hi, 
I reviewed your PR. Thanks a lot for it!
Since you have interest I added you as a collaborator so I do not hold back your work.
I may also dig out code for doc2text.com I have and spin it up so we can test it online. It is useful indeed to translate manager docx files into nice md files :)

**Comment by bostko** [comment]
Please rise specific questions about projects future in new issues. I will close this one.
