### ISSUE TITLE
RFE: Create as an extension for LibO/AOo

### ISSUE THREAD

**Issue by nognkantoor** [bostko/doc2text#9]
Would it be possible to create this as an extension for LibreOffice/Apache OpenOffice.
Export as MarkDown formatted file.

##

I realize the language used (ruby) might be a problem, because most Libo/AOo configurations don't include ruby as a macro language.  The quasi-workaround is to provide some instructions on installing and configuring ruby as macro language for LibO/AOo.

**Comment by bostko** [comment]
@nognkantoor good alternative is http://doc2text.com
